name: Build and Publish Utilities

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  get-version-no:
    uses: ./.github/workflows/get-version-no.yml
  build-test-publish-0:
    name: Process utilities set 0
    strategy:
      fail-fast: true
      matrix:
        utility-project-name:
          - SmingCode.Utilities.Data
          - SmingCode.Utilities.DelegateInvokers
          - SmingCode.Utilities.Logging.AspNetCore
          - SmingCode.Utilities.MinimalApi
          - SmingCode.Utilities.ProcessTracking
          - SmingCode.Utilities.ServiceMetadata
          - SmingCode.Utilities.StartupProcesses
          - SmingCode.Utilities.Testing.AutoDomainData
    needs: get-version-no
    uses: ./.github/workflows/build-test.yml
    with:
      project-name: '${{ matrix.utility-project-name }}'
      version-no: ${{ needs.get-version-no.outputs.next-version }}
  build-test-publish-1:
    name: Process utilities set 1
    strategy:
      fail-fast: true
      matrix:
        utility-project-name:
          - SmingCode.Utilities.ServiceApiClient
          - SmingCode.Utilities.ServiceMetadata.WebApplicationStartup
          - SmingCode.Utilities.StartupProcesses.AspNetCore
    needs: [ get-version-no, build-test-publish-0 ]
    uses: ./.github/workflows/build-test.yml
    with:
      project-name: '${{ matrix.utility-project-name }}'
      version-no: ${{ needs.get-version-no.outputs.next-version }}
  build-test-publish-2:
    name: Process utilities set 2
    strategy:
      fail-fast: true
      matrix:
        utility-project-name:
          - SmingCode.Utilities.Kafka
          - SmingCode.Utilities.Kafka.MinimalConsumers
          - SmingCode.Utilities.ProcessTracking.WebApi
    needs: [ get-version-no, build-test-publish-1 ]
    uses: ./.github/workflows/build-test.yml
    with:
      project-name: '${{ matrix.utility-project-name }}'
      version-no: ${{ needs.get-version-no.outputs.next-version }}
  build-test-publish-3:
    name: Process utilities set 3
    strategy:
      fail-fast: true
      matrix:
        utility-project-name:
          - SmingCode.Utilities.Kafka.Host
          - SmingCode.Utilities.ProcessTracking.Kafka
    needs: [ get-version-no, build-test-publish-2 ]
    uses: ./.github/workflows/build-test.yml
    with:
      project-name: '${{ matrix.utility-project-name }}'
      version-no: ${{ needs.get-version-no.outputs.next-version }}
  create-release:
    name: Create release
    needs: [ build-test-publish-3, get-version-no ]
    uses: ./.github/workflows/add-github-release.yml
    with:
      version-number: ${{ needs.get-version-no.outputs.next-version }}
      previous-tag: ${{ needs.get-version-no.outputs.last-version-tag }}